### ISSUE TITLE
Fails to build with guile > 2.0 installed on host

### ISSUE THREAD

**Issue by sherrbc1** [riscv/riscv-binutils-gdb#109]
From what I gather online, this seems to have been an issue since upstream guile deprecated structures used by gdb.

https://sourceware.org/bugzilla/show_bug.cgi?id=21104
https://github.com/crosstool-ng/crosstool-ng/issues/799
http://archive.linuxfromscratch.org/mail-archives/blfs-dev/2017-March/033056.html
https://github.com/crosstool-ng/crosstool-ng/issues/718

[Upstream GDB](https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blobdiff;f=gdb/configure;h=6b445e4f6757c94109d433fcb921968c5b895271;hp=4d473cc934cd3b4e72509ae5114fb0cd1112ce2d;hb=6e66f7538112d2f5fb1af17dbde33ba37a7171be;hpb=8e464506d2131fc931c4f81a22cc7125b7adf434) side-stepped the issue last week by defaulting to guile 2.0 unless otherwise specified. The suggested fix is to include `--without-guile` or `--with-guile=no` in GDB's configure scripts. My system has guile 2.2.2 installed, which explains the inability to find the missing types. It is likely that installing an earlier version of Guile would also remedy the situation. 

This issue was posted [here](https://github.com/riscv/riscv-tools/issues/138) before I realized the specifics of the problem.

**Comment by jim-wilson** [comment]
We added a --with-guile configure option to riscv-gnu-toolchain to pass down to gdb.  So if you git clone riscv-gnu-toolchain, and then use --with-guile=no when configuring, gdb will build even if you have the incompatible guile-2.2 installed.

It would not be appropriate for us to modify gdb configure scripts.  Upstream gdb will no longer try to use guile-2.2 by default, so upstream gdb will build OK by default on systems with guile-2.2.2, and once that gets merged into our riscv-binutils-gdb tree, we will be OK too.

Meanwhile our workaround is to configure riscv-gnu-toolchain using --with-guile=no.
