### ISSUE TITLE
GDB building without TUI support

### ISSUE THREAD

**Issue by sherrellbc** [riscv/riscv-binutils-gdb#134]
I was developing on an Arch Linux machine for some time and was using the GDB binary compiled together when building [riscv-tools](https://github.com/riscv/riscv-tools/blob/master/README.md). However, I have recently needed to begin working from an Ubuntu machine. So, I set forth and recloned/compiled riscv-tools after installing the necessary packages (see the riscv-tools link). However, only this time GDB was compiled without Text User Interface ([TUI](https://sourceware.org/gdb/onlinedocs/gdb/TUI-Commands.html)) support (e.g. _layout_, _focus_).

It seems likely that the lack of certain packages during configuration resulted in some subset of features being disabled. What are the required packages/dependencies so that GDB will build with TUI support?

**Comment by ilg-ul** [comment]
it might not be exactly your case, but in some of my GNU MCU Eclipse builds I noticed GDB to have a reference to ncurses.so.

**Comment by sherrellbc** [comment]
@ilg-ul Thanks for responding so quickly. I figured it was related to curses, but I made sure to have that package installed (`libncurses5`) on Ubuntu. 

I've been poking around a bit in `configure.ac` and found a few things:

Should TUI be included at all:
https://github.com/riscv/riscv-binutils-gdb/blob/5852e73c72dbb9b86daf36c5c8afb26f2d292ef3/gdb/configure.ac#L558-L561

If so, check to see if curses is installed:
https://github.com/riscv/riscv-binutils-gdb/blob/5852e73c72dbb9b86daf36c5c8afb26f2d292ef3/gdb/configure.ac#L563-L577

Include TUI source:
https://github.com/riscv/riscv-binutils-gdb/blob/5852e73c72dbb9b86daf36c5c8afb26f2d292ef3/gdb/configure.ac#L579-L596

This seems to be the only dependency, but it doesn't seem to find my installation. Perhaps it is located in a directory that is not searched, like one of the comments alludes to.

**Comment by ilg-ul** [comment]
check `config.log`, perhaps you can spot something.

alternately you can start configure with `bash -x configure ...` and you will see exactly what the script is doing.

**Comment by sherrellbc** [comment]
I did not find anything in `config.log` (notably `ac_cv_search_waddstr`). This tag does not appear at all, actually. 

I tried `./configure --enable-tui` and was met with `configure: error: no enhanced curses library found; disable TUI` when building. 

I must misunderstand the process as I was expecting this to be an error at "configure" time, not compile-time.

**Comment by jim-wilson** [comment]
You need the libncurses5-dev package.  On ubuntu, libncurses5 contains the libraries necessary to run programs compiled with curses.  libncurses5-dev contains the packages necessary to compile programs with curses.  Installing the -dev package installs both of them.

**Comment by ilg-ul** [comment]
Ah, Jim is right, for each library required by the build you need the headers and possibly other files, which are usually in a corresponding `-dev` package.

**Comment by sherrellbc** [comment]
That was it. Thanks for the help.

**Comment by sherrellbc** [comment]
Unfortunately other features seem to not work as well now. For instance, `next`, or `ni` seems to behave exactly like `step`/`si`.
