### ISSUE TITLE
GDB support to Remote Serial Protocol (RSP) over a TCP/IP connection

### ISSUE THREAD

**Issue by lucaslpaixao** [riscv/riscv-binutils-gdb#150]
Hi, I would like to know if the latest GDB version in this repo fully supports the connection to a target using the Remote Serial Protocol (RSP) over a TCP/IP connection. Thanks!

**Comment by jim-wilson** [comment]
The latest gdb can be found upstream at http://sourceware.org/gdb.  The one here is out-of-date, and is a dead end, as it is different from the upstream one.  We don't have a dedicated gdb maintainer here, but there is one upstream.  Both this gdb and the upstream one are somewhat working, but if you want to know if a particular feature works, you will probably have to try it and see.  We mostly use this gdb with openocd to talk to the target via jtag.  I don't know if target remote works.

The upstream maintainer gave a talk at the recent Barcelona conference.  Tuesday at 1:45.
https://riscv.org/2018/05/risc-v-workshop-in-barcelona-proceedings/
