### ISSUE TITLE
gdb 8.1.1

### ISSUE THREAD

**Issue by berolinux** [riscv/riscv-binutils-gdb#158]
gdb 8.1.1 has been released and fixes a couple of problems I've had with riscv-gdb-8.1 (such as compiling with Python 3.7).

The RISC-V patches rebase cleanly except for the changelog entries.

I've created a riscv-gdb-8.1.1 branch in my fork of the repository:
https://github.com/berolinux/riscv-binutils-gdb/tree/riscv-gdb-8.1.1

I don't think github supports sending a pull request that would create a new branch - so submitting a "manual" pull request instead.

**Comment by palmer-dabbelt** [comment]
Thanks!  I believe I've managed to create the branch, so I'm closing this.

We should swap riscv-gnu-toolchain over to point to this, do you mind giving the tests a run and opening a PR?  I'd love to be able drop our old hacked up branch based on a binutils release :)
