### ISSUE TITLE
GDB : NON-STOP Mode

### ISSUE THREAD

**Issue by rajeshkrmeena** [riscv/riscv-binutils-gdb#164]
I tried to turn on gdb non-stop mode  through three commands:
(gdb) set pagination off 
(gdb) set target-async on
(gdb) set non-stop on
But when tried to connect remote target, unable to connect
(gdb) target extended-remote localhost:3333
Remote debugging using :3333
**Non-stop mode requested, but remote does not support non-stop** (GDB message)
How can the support for non-stop mode enable for ### remote target in riscv-toolchain GDB ?

(special note : Spike-rtos.cfg used in openocd configuration for multiple riscv cores)

**Comment by jim-wilson** [comment]
We have only basic gdb features implemented at present.  It will likely be a while before someone volunteers to implement the non-stop support.

**Comment by rajeshkrmeena** [comment]
Thanks @jim-wilson
