### ISSUE TITLE
GDBserver failing due to Remote register badly formatted..

### ISSUE THREAD

**Issue by cghalibkhan** [riscv/riscv-binutils-gdb#226]
Hello,

I have build an GDBServer on **U540 Board** with the following step's,

1. git clone https://github.com/riscv/riscv-binutils-gdb.git
2. cd riscv-binutils-gdb/ && mkdir build install && cd build/ 
3. ../configure --prefix=$PWD/../install --enable-gdbserver 
4. make all-gdbserver 
5. make install-gdbserver 
6. ls ../install/bin/
      gdbserver

                                        **Testing:**
In Testing i have hit with an Error like **Remote register badly formatted:**
**Can any one know How to over come this Issue**

**TARGET**
**$ ./gdbserver localhost:2000 hello**
Process /home/root/khan/riscv-binutils-gdb/install/bin/hello created; pid = 23687
Listening on port 2000
Remote debugging from host ::ffff:10.XXX.X.33, port 49940
**Remote side has terminated connection.  GDBserver will reopen the connection.**
Listening on port 2000

**HOST**
**$ gdb**                                                                                                                                      
..
(gdb) 
**(gdb) target remote 10.XXX.X.76:2000**
Remote debugging using 10.XXX.X.76:2000
**warning: while parsing target description (at line 4): Target description specified unknown architecture "riscv:rv64id"**
warning: Could not load XML target description; ignoring
Reading /home/root/khan/riscv-binutils-gdb/install/bin/hello from remote target...
warning: File transfers from remote targets can be slow. Use "set sysroot" to access files locally instead.
Reading /home/root/khan/riscv-binutils-gdb/install/bin/hello from remote target...
Reading symbols from target:/home/root/khan/riscv-binutils-gdb/install/bin/hello...done.
**Remote register badly formatted: T0502:40fcffff3f000000;20:005ffef73f000000;thread:p5c87.5c87;core:1;
here: 3f000000;20:005ffef73f000000;thread:p5c87.5c87;core:1;**

**Comment by jim-wilson** [comment]
You asked the same question is at least 3 different places.  That is annoying and creates extra work for me.  Please stop doing that.  Answered elsewhere.
