### ISSUE TITLE
riscv-binutils-2.35-rvb: wrong match for xperm.h

### ISSUE THREAD

**Issue by rdolbeau** [riscv/riscv-binutils-gdb#251]
Hello,

at: https://github.com/riscv/riscv-binutils-gdb/blob/3e5f50f31348d05144966545d862a3172d315230/include/opcode/riscv-opc.h#L378

The match value is wrong and should be:
`#define MATCH_XPERMH 0x28006033` (6 instead of 3 for bits 15-12).

as according to the current bitmanip draft, funct3 for xperm.h is `110` (and not `011`). The other forms (`.b`, `.n` and `.w`) are correct.

**Comment by Nelson1225** [comment]
Thanks for sending the PR.
The riscv-binutils-2.35-rvb branch is obsolete for now.  I think all the rvb related branches here can only guarantee the implementation of the frozen ZBA, ZBB and ZBC.  There are no branches here are working on the draft rvb currently.  I'm not sure if we will continue to do the following work in the riscv-binutils-2.35-rvb, or in the other branches, we will figure this out soon.  Thanks.
