### ISSUE TITLE
gdb can't distinguish 32- from 64-bit targets

### ISSUE THREAD

**Issue by timsifive** [riscv/riscv-binutils-gdb#54]
If you start a 64-bit gdb, and immediately connect it to a 32-bit target, gdb will think the target is 64 bits. Register values won't be interpreted correctly, and generally the setup is unusable. If you give gdb an ELF file, it will find XLEN from there. You can also explicitly force gdb to 32-bit using `set arch riscv:rv32`.

To solve this nicely, the server gdb connects to (eg. OpenOCD) would have to return a different target description for RV32 versus RV64 cores. https://sourceware.org/ml/gdb/2016-10/msg00015.html describes roughly what work is required to accomplish this.

**Comment by TM1234** [comment]
I presume that there is a typo in the original post and...

> If you start a 64-bit gdb, and immediately connect it to a 32-bit target, gdb will think the target is 32 bits. 

Should read...

> If you start a 64-bit gdb, and immediately connect it to a 32-bit target, gdb will think the target is 64 bits. 

Is that correct?

**Comment by timsifive** [comment]
@TM1234: Yes. I fixed it in the original comment.

**Comment by TM1234** [comment]
Thanks Tim. :-)

**Comment by timsifive** [comment]
Confirmed that this is fixed with gdb/openocd from their respective xml_registers branches (which have merged to their mainlines).

**Comment by TM1234** [comment]
Does this mean that it's no longer necessary to explicitly pass set arch riscv:rv32 when connecting to a 32 bit target?

**Comment by timsifive** [comment]
Yes.
