### ISSUE TITLE
riscv-binutils-gdb won't build on macos

### ISSUE THREAD

**Issue by mwachs5** [riscv/riscv-binutils-gdb#69]
```
riscv-gnu-toolchain/riscv-binutils-gdb/gdb/common/gdb_unlinker.h:35:35: error: '__nonnull__' attribute is invalid for the implicit this argument
  unlinker (const char *filename) ATTRIBUTE_NONNULL (1)
```

**Comment by aswaterman** [comment]
Looks like that's in code that's out of control... which gcc version are you using?  (or clang. for that matter)

**Comment by mwachs5** [comment]
```
>> gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin****
```

**Comment by aswaterman** [comment]
Seems like this is fixed upstream: http://patchwork.sourceware.org/patch/19480/

Can you manually apply that fix and see if it works?  If so, maybe we'll have to backport the patch to this branch... what do you think @palmer-dabbelt

**Comment by palmer-dabbelt** [comment]
If it works then it'll be easy to maintain.

**Comment by palmer-dabbelt** [comment]
This was at least building for the SDK release, so I think this has been fixed.
