### ISSUE TITLE
Bad comment in elfxx-riscv.c?

### ISSUE THREAD

**Issue by palmer-dabbelt** [riscv/riscv-binutils-gdb#89]
@kuanlinchentw I think this comment is wrong: https://github.com/riscv/riscv-binutils-gdb/blob/riscv-next/bfd/elfxx-riscv.c#L837

**Comment by kuanlinchentw** [comment]
Yes, it's wrong. I think the comment should be "32-bit PC relative".  Could you help me fix it, please?

**Comment by palmer-dabbelt** [comment]
Fixed, thanks!
